---
# generic settings
main_username: "souldeity"
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# ferrarimarco.bash-aliases
bash_aliases:
  - { alias: "ls", command: "ls --color=auto"}
  - { alias: "ll", command: "ls -la"}
  - { alias: "df", command: "df -h -x aufs -x tmpfs -x udev"}
  - { alias: "du", command: "du -ch"}
  - { alias: "c", command: "clear"}
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`"}
  - { alias: "drm", command: "docker rm `docker ps -aq`"}
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml --remove-orphans "}
  - { alias: "dprune", command: "docker image prune"}
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "appdata", command: "cd {{ status_appdata_path }}" }

# grog.package
package_list:
  - name: aptitude
  - name: bash-completion
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: mutt
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: open-vm-tools
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# ironicbadger.ansible_users
users:
  - username: "{{ main_username }}"
    github_username: "{{ main_username }}"
    name: "{{ main_username }}"
    groups: ['wheel']
    uid: "{{ main_uid }}"
groups_to_create:
  - name: "{{ main_groupname }}"
    gid: "{{ main_gid }}"
  - name: wheel

# weareinteractive.environment
environment_config: {
  "PUID": "{{ main_gid }}",
  "PGID": "{{ main_gid }}"
}

# geerlingguy.ntp
ntp_timezone: "America/Chicago"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - "{{ main_username }}"

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
#  - "UID={{ main_uid }}"
#  - "GID={{ main_gid }}"
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/souldeity

# influxdb
influxdb_ip: 192.168.1.201
influxdb_port: 8086

## telegraf
telegraf_influxdb_urls:
  - "http://{{ influxdb_ip }}:{{ influxdb_port }}"
telegraf_influxdb_database: telegraf
telegraf_influxdb_username: root
telegraf_influxdb_password: root
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      perdevice: "true"
  - name: hddtemp
  - name: net
    options:
      interfaces:
        - "ens192"
  - name: sensors
