---

target_os: debian
bastion_hostname: soulbastion

# soulfigurine
figurine_name: "{{ bastion_hostname }}"

# grog.package
package_list:
  - name: wireguard

# ironicbadger.docker_compose_generator
compose_schema_version: 3
appdata_path: /home/souldeity/appdata
containers:
  - service_name: wireguard
    active: true
    image: linuxserver/wireguard
    volumes:
      - "{{ appdata_path }}/wireguard:/config"
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    environment:
      - "PEERS=fold2 1400-L soullaptop"
      - "SERVERURL={{ secret_wireguard_url }}"
      - "SERVERPORT={{ secret_wireguard_port }}"
      - "ALLOWEDIPS=0.0.0.0/0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    ports:
      - "{{ secret_wireguard_port }}:51820/udp"
    sysctl:
      - net.ipv4.conf.all.src_valid_mark=1
    include_global_env_vars: true
    restart: unless-stopped
