---
target_os: debian
bastion_hostname: soulbastion

# ironicbadger.figurine
figurine_name: "{{ bastion_hostname }}"

# grog.package
package_list:
  - name: qemu-guest-agent
  - name: wireguard

# ironicbadger.docker_compose_generator
compose_schema_version: 3
appdata_path: /home/souldeity/appdata
containers:
###
  - service_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    hostname: wireguard
    active: true
    volumes:
      - "{{ appdata_path }}/wireguard:/config"
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    environment:
      - "SERVERURL={{ secret_wireguard_url }}"
      - "SERVERPORT={{ secret_wireguard_port }}"
      - "PEERS=2"
      - "PEERDNS=auto"
      - "ALLOWEDIPS=0.0.0.0/0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    ports:
      - "{{ secret_wireguard_port }}:51820/udp"
    sysctl:
      - net.ipv4.conf.all.src_valid_mark=1
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: guac
    image: jasonbean/guacamole
    container_name: guac
    hostname: guac
    active: false
    volumes:
      - "{{ appdata_path }}/guacamole:/config"
    environment:
      - OPT_MYSQL=Y
      - OPT_TOTP=Y
    ports:
      - "8080:8080"
    include_global_env_vars: true
    restart: unless-stopped
  ###

  # template for docker-compose services
#  - service_name:
#    image:
#    container_name:
#    hostname:
#    active: true
#    volumes:
#      - "{{ appdata_path }}/app:/config"
#    environment:
#      - 
#    ports:
#      - 
#    include_global_env_vars: true
#    restart: unless-stopped
  ###