---

target_os: debian

# soulfigurine
figurine_name: soulbastion

# ironicbadger.ansible_users
users:
  - username: "{{ main_username }}"
    github_username: "{{ main_username }}"
    name: "{{ main_username }}"
    groups: ['wheel']
    uid: "{{ main_uid }}"
groups_to_create:
  - name: "{{ main_groupname }}"
    gid: "{{ main_gid }}"
  - name: wheel

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: htop
  - name: mutt
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: open-vm-tools
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: wireguard

# geerlingguy.security
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true

# geerlingguy.docker
docker_users:
  - "{{ main_username }}"

# ironicbadger.docker_compose_generator
compose_schema_version: 3
appdata_path: /home/souldeity/appdata
containers:
  - service_name: wireguard
    active: true
    image: linuxserver/wireguard
    volumes:
      - "{{ appdata_path }}/wireguard:/config"
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    environment:
      - "PEERS=fold2 1400-L"
      - "SERVERURL={{ secret_wireguard_url }}"
      - "SERVERPORT={{ secret_wireguard_port }}"
      - "ALLOWEDIPS=0.0.0.0/0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    ports:
      - "{{ secret_wireguard_port }}:51820/udp"
    sysctl:
      - net.ipv4.conf.all.src_valid_mark=1
    include_global_env_vars: true
    restart: unless-stopped
