---
cloud_hostname: soulcloud
main_username: souldeity

# ironicbadger.figurine
figurine_name: "{{ cloud_hostname }}"

# ironicbadger.ansible_role_bash_aliases
bash_aliases:
  - { alias: "ls", command: "ls --color=auto"}
  - { alias: "ll", command: "ls -la"}
  - { alias: "df", command: "df -h -x aufs -x tmpfs -x udev"}
  - { alias: "du", command: "du -ch"}
  - { alias: "c", command: "clear"}
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml up -d --remove-orphans"}
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "appdata", command: "cd /mnt/disk1/appdata" }

# soultraefik
traefik_file_provider: false
traefik_enable_dashboard: false #defaults to false
traefik_insecure_transport: true #defaults to false
traefik_exposed_by_default: true

# soulrestic
restic_backup_locations:
  - "{{ appdata_path }}"
restic_forget: true #defaults to false

# ironicbadger.docker_compose_generator
appdata_path: /mnt/disk1/appdata
containers:
###
  - service_name: tr
    active: true
    image: traefik
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    extra_hosts:
      - host.docker.internal:172.17.0.1
    environment:
      - "CLOUDFLARE_EMAIL={{ secret_cloudflare_email }}"
      - "CLOUDFLARE_API_KEY={{ secret_cloudflare_api }}"
    volumes:
      - "{{ appdata_path }}/traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
###
  - service_name: uptime-kuma
    active: true
    image: louislam/uptime-kuma
    labels:
      - traefik.http.routers.uptime.rule=Host(`uptime.{{ secret_domain_cloud }}`)
    volumes:
      - "{{ appdata_path }}/uptime-kuma:/app/data"
    restart: unless-stopped
###
  - service_name: healthchecks
    active: true
    image: lscr.io/linuxserver/healthchecks
    labels:
      - "traefik.http.routers.healthchecks.rule=Host(`hc.{{ secret_domain_cloud }}`)"
    volumes:
      - "{{ appdata_path }}/healthchecks:/config"
    environment:
      - APPRISE_ENABLED=True
      - DEBUG=False
      - PING_BODY_LIMIT=100000
      - SITE_NAME=Health Checks
      - "SITE_ROOT=https://hc.{{ secret_domain_cloud }}"
      - "SUPERUSER_EMAIL={{ secret_hc_email }}"
      - "SUPERUSER_PASSWORD={{ secret_hc_pass }}"
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: it-tools
    active: true
    image: ghcr.io/corentinth/it-tools
    labels:
      - "traefik.http.routers.ittools.rule=Host(`tools.{{ secret_domain_cloud }}`)"
    restart: unless-stopped
###
  - service_name: librespeed
    active: true
    image: lscr.io/linuxserver/librespeed
    labels:
      - "traefik.http.routers.librespeed.rule=Host(`speed.{{ secret_domain_full }}`)"
    volumes:
      - "{{ appdata_path }}/librespeed:/config"
    include_global_env_vars: true
    restart: unless-stopped
###