---
# soul-dhcp-dns (pihole)
dnsmasq_config_dir: /etc/dnsmasq.d
pihole_config_dir: /etc/pihole
running_as_container: false

default_domain: "{{ secret_domain_local }}"
network_cidr: 10.42.0.0/20
dhcp_range_start: 10.42.7.100
dhcp_range_end: 10.42.7.250
dhcp_router: 10.42.0.254
dhcp_active: "true"
pxe_server_ip: 10.42.1.1
#lancache_ip: 10.42.1.20 # not in use

dns_overrides:
  # try to use sparingly and must be FQDN
  - {ip: 10.42.0.252, custom_dns: "{{ secret_domain_local }}"} # catch-all for caddy
  - {ip: 10.42.0.252, custom_dns: "opnsense.{{ secret_domain_local }}"} # overrides named node
  - {ip: 10.42.0.252, custom_dns: "dns.{{ secret_domain_local }}"}
  - {ip: 10.42.1.1, custom_dns: "soulpms.{{ secret_domain_local }}"} # overrides named node
  - {ip: 10.42.2.1, custom_dns: "frigate.{{ secret_domain_local }}"}
  - {ip: 10.42.1.1, custom_dns: "home.{{ secret_domain_full }}"}
  - {ip: 10.42.1.1, custom_dns: "print.{{ secret_domain_local }}"}
  - {ip: 10.42.1.1, custom_dns: "print2.{{ secret_domain_local }}"}
  - {ip: 10.42.0.250, custom_dns: "unifi"}
  - {ip: 10.42.0.250, custom_dns: "inform.unifi.{{ secret_domain_local }}"}
  - {ip: 10.42.0.252, custom_dns: "proxmox.n.{{ secret_domain_local }}"}
  - {ip: 10.42.0.252, custom_dns: "proxmox.p.{{ secret_domain_local }}"}
  - {ip: 10.42.0.252, custom_dns: "start.{{ secret_domain_local }}"}

dhcp_reservations:
  # Network Infrastructure
  ## soulnet - Proxmox Host - Network VM/Containers
  - {mac: f4:93:9f:ef:dd:75, ip: 10.42.0.1, hostname: soulnet, custom_dns: ["n"]}
  #- {mac: 90:e2:ba:4f:d7:b3, ip: WAN, hostname: opnsenseWAN} # WAN DHCP - passed through#
  #- {mac: 90:e2:ba:4f:d7:b2, ip: 10.42.0.254, hostname: opnsense} # LAN - passed through#
  ### soulnet services
  - {mac: BC:24:11:61:9A:3E, ip: 10.42.0.250, hostname: unifi}
  #- {mac: CE:87:AE:C2:BB:AE, ip: 10.42.0.251, hostname: nginx} # not in use
  - {mac: BC:24:11:70:5A:44, ip: 10.42.0.252, hostname: caddy}
  - {mac: BC:24:11:90:0A:9C, ip: 10.42.0.253, hostname: pihole}
  - {mac: 70:54:d2:45:9d:86, ip: 10.42.0.254, hostname: opnsense, custom_dns: ["opnsense.firewall"]}

  #########
  ## networking equipment
  ### poe switches
  - {mac: 00:19:56:08:2c:00, ip: 10.42.0.2, hostname: cisco-catalyst-3560g-48ps}
  - {mac: 80:2a:a8:dc:44:22, ip: 10.42.0.5, hostname: unifi-edgeswitch-24-500w}

  ### wifi
  - {mac: 60:22:32:fe:9c:e0, ip: 10.42.0.3, hostname: unifi-u6-pro-upstairs}
  - {mac: 74:ac:b9:a3:d9:a1, ip: 10.42.0.4, hostname: unifi-u6-lite-basement}

  ## soulpms - Proxmox Host - Perfect Media Server
  - {mac: 30:9c:23:a5:a9:b6, ip: 10.42.1.1, hostname: soulpms, custom_dns: ["p"]}
  ### soulpms services
  - {mac: BC:24:11:B0:A1:91, ip: 10.42.10.101, hostname: soulcrypto}
  - {mac: 02:90:d9:fa:23:c5, ip: 10.42.10.200, hostname: soulpelican}
  - {mac: ca:79:1d:57:e7:c1, ip: 10.42.10.201, hostname: soulwing}

  ## soulhass - Home Assistant Server
  - {mac: f4:93:9f:ef:10:6d, ip: 10.42.1.2, hostname: soulhass}

  #########
  ## misc servers
  - {mac: dc:a6:32:1c:0f:7a, ip: 10.42.1.10, hostname: soulprint} #pi4 4gb
  - {mac: dc:a6:32:21:80:72, ip: 10.42.1.11, hostname: soulprint2} #pi4 4gb
  - {mac: 24:58:7c:d7:41:14, ip: 10.42.1.12, hostname: soulp1s} #bambu p1s

  #########
  ## media players and TVs
  - {mac: 48:b0:2d:09:4d:21, ip: 10.42.1.100, hostname: shield-living-room}
  - {mac: 48:b0:2d:c2:7e:7c, ip: 10.42.1.101, hostname: shield-family-room}
  - {mac: 20:3d:bd:95:08:fd, ip: 10.42.1.102, hostname: lg-living-room-tv}
  - {mac: 80:5b:65:de:1c:c4, ip: 10.42.1.103, hostname: lg-family-room-tv}
  - {mac: 8c:49:62:4b:65:cc, ip: 10.42.1.104, hostname: roku-bedroom}
  - {mac: 6c:56:97:53:f4:cb, ip: 10.42.1.105, hostname: firetv-guest}
  - {mac: 00:06:78:b6:0a:72, ip: 10.42.1.106, hostname: denon-living-room-avr}

  #########
  ## cameras (PoE, WIFI)
  - {mac: 8c:ec:4b:75:17:8e, ip: 10.42.2.1, hostname: soulfrigate}

  - {mac: 48:9e:9d:d8:84:d5, ip: 10.42.2.10, hostname: reolink-doorbell}
  - {mac: ec:71:db:82:72:26, ip: 10.42.2.11, hostname: reolink-driveway}
  - {mac: b4:6d:c2:c4:57:e4, ip: 10.42.2.12, hostname: reolink-garage}
  - {mac: b4:6d:c2:c5:7a:55, ip: 10.42.2.13, hostname: reolink-cayden}

  - {mac: c0:6d:1a:f3:19:46, ip: 10.42.2.20, hostname: wyze-workbench}

  #########
  ## local IoT
  - {mac: 68:ff:7b:01:d9:21, ip: 10.42.5.10, hostname: tplink-plug-bedroom}
  - {mac: d8:0d:17:9a:a4:f1, ip: 10.42.5.11, hostname: tplink-plug-living-room}
  - {mac: d8:0d:17:9a:77:5b, ip: 10.42.5.12, hostname: tplink-plug-family-room}
  - {mac: 68:ff:7b:01:c9:2b, ip: 10.42.5.13, hostname: tplink-plug-workbench}
  - {mac: c4:d8:d5:0b:d4:b4, ip: 10.42.5.20, hostname: ratgdo-garage-door}

  #########
  ## cloud IoT
  - {mac: 64:90:c1:19:ee:2b, ip: 10.42.5.200, hostname: roborock-vacuum}
  - {mac: 64:16:66:af:52:a6, ip: 10.42.5.201, hostname: nest-thermostat}
  - {mac: 00:17:88:68:f7:01, ip: 10.42.5.202, hostname: hue-bridge}
  - {mac: f8:a2:6d:58:67:23, ip: 10.42.5.203, hostname: canon-printer}
  - {mac: cc:6a:10:ad:4b:84, ip: 10.42.5.204, hostname: myq-garage-opener}
  - {mac: 48:e7:29:c0:9f:00, ip: 10.42.5.205, hostname: hatch-rest-cayden}
  - {mac: b0:b2:1c:af:c9:5c, ip: 10.42.5.206, hostname: hatch-rest-bedroom}
  - {mac: b0:4a:39:c8:10:c9, ip: 10.42.5.207, hostname: roborock-vacuum-a125}
  - {mac: 04:c2:9b:fa:6b:57, ip: 10.42.5.208, hostname: aura-picture-frame}
  - {mac: 60:74:f4:bf:1a:56, ip: 10.42.5.209, hostname: govee-outdoor-lights}
  
  ## Voice assistant boxes
  - {mac: f4:f5:d8:df:a0:ca, ip: 10.42.5.210, hostname: google-home}
  - {mac: 1c:f2:9a:07:e2:8b, ip: 10.42.5.211, hostname: google-hub-bedroom}
  - {mac: 1c:f2:9a:11:e4:bb, ip: 10.42.5.212, hostname: google-hub-family-room}
  - {mac: 48:d6:d5:e6:75:41, ip: 10.42.5.213, hostname: google-mini-workbench}
  - {mac: e4:f0:42:3d:20:55, ip: 10.42.5.214, hostname: google-mini-guest-room}

  #########
  ## primary clients (desktop, servers, laptops, phones, tablets)
  - {mac: f0:2f:74:18:35:8f, ip: 10.42.3.10, hostname: souldesktop} # personal workstation 
  - {mac: b0:7d:64:14:f3:84, ip: 10.42.3.11, hostname: soullaptop} # personal laptop 
  - {mac: 04:cf:4b:22:b3:66, ip: 10.42.3.12, hostname: 1111-l} # work laptop 
  - {mac: 64:5d:f4:5b:6a:04, ip: 10.42.3.13, hostname: nick-phone}
  - {mac: a6:85:3b:8c:7b:1c, ip: 10.42.3.14, hostname: nick-watch}
  - {mac: 50:5a:65:81:62:d7, ip: 10.42.3.15, hostname: souldeck}

  - {mac: 1c:91:80:cc:85:f7, ip: 10.42.3.50, hostname: heather-macbook} # work laptop
  - {mac: be:b7:62:2f:ed:6a, ip: 10.42.3.51, hostname: heather-phone}
  - {mac: ee:f9:98:03:5b:36, ip: 10.42.3.52, hostname: heather-watch}
  - {mac: 5e:ec:50:8c:8f:a9, ip: 10.42.3.53, hostname: heather-tablet}