---

pms_ip: 192.168.1.111
pms_hostname: soulpms

# soulfigurine
figurine_name: soulpms

# soultraefik
traefik_file_provider: true
traefik_enable_dashboard: false #defaults to false
traefik_insecure_transport: false #defaults to false

# ironicbadger.docker_compose_generator
compose_schema_version: 3
containers:
  ###
  - service_name: traefik
    container_name: traefik
    active: true
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    extra_hosts:
      - host.docker.internal:172.17.0.1
    environment:
      - "CLOUDFLARE_EMAIL={{ secret_cloudflare_email }}"
      - "CLOUDFLARE_API_KEY={{ secret_cloudflare_api }}"
    volumes:
      - "{{ appdata_path }}/traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

# template for docker-compose services
#  - service_name:
#     active: true
#     image:
#     container_name: #optional - only required if diff to service_name
#     labels:
#       - traefik.enable=true
#       - "traefik.http.routers.XXXX.rule=Host(`XXXX.{{ main_domain }}`)"
#       - traefik.http.routers.XXXX.entrypoints=websecure
#       - traefik.http.routers.XXXX.tls.certresolver=cloudflare
#       - traefik.http.services.XXXX.loadbalancer.server.port=PORTHERE
#     volumes:
#       - "{{ appdata_path }}/app:/config"
#     environment:
#       -
#     include_global_env_vars: #optional - defaults to false
#     restart: unless-stopped
