---

pms_hostname: soulpms

# soulfigurine
figurine_name: "{{ pms_hostname }}"

# ironicbadger.docker_compose_generator
compose_schema_version: 3
containers:
  ###
  
# template for docker-compose services
#  - service_name:
#     active: true
#     image:
#     container_name: #optional - only required if diff to service_name
#     labels:
#       - traefik.enable=true
#       - "traefik.http.routers.XXXX.rule=Host(`XXXX.{{ main_domain }}`)"
#       - traefik.http.routers.XXXX.entrypoints=websecure
#       - traefik.http.routers.XXXX.tls.certresolver=cloudflare
#       - traefik.http.services.XXXX.loadbalancer.server.port=PORTHERE
#     volumes:
#       - "{{ appdata_path }}/app:/config"
#     environment:
#       -
#     include_global_env_vars: #optional - defaults to false
#     restart: unless-stopped
