---

status_hostname: soulstatus

# soulfigurine
figurine_name: "{{ status_hostname }}"

# soultraefik
traefik_file_provider: false
traefik_enable_dashboard: false
traefik_insecure_transport: false

# ironicbadger.docker_compose_generator
compose_schema_version: 3
containers:
###
  - service_name: traefik
    active: true
    image: traefik
    container_name: traefik
    ports:
        - 80:80
        - 443:443
    volumes:
        - "{{ appdata_path }}/traefik:/etc/traefik"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        - "CLOUDFLARE_EMAIL={{ secret_cloudflare_email }}"
        - "CLOUDFLARE_API_KEY={{ secret_cloudflare_api }}"
    restart: unless-stopped
###
  - service_name: smokeping
    active: true
    image: linuxserver/smokeping
    volumes:
      - "{{ appdata_path }}/smokeping/config:/config"
      - "{{ appdata_path }}/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.smokeping.rule=Host(`ping.{{ secret_domain_full }}`)"
      - traefik.http.routers.smokeping.entrypoints=websecure
      - traefik.http.routers.smokeping.tls.certresolver=cloudflare
      - traefik.http.services.smokeping.loadbalancer.server.port=80
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: librespeed
    active: true
    image: linuxserver/librespeed
    labels:
      - traefik.enable=true
      - "traefik.http.routers.librespeed.rule=Host(`speed.{{ secret_domain_full }}`)"
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.routers.librespeed.tls.certresolver=cloudflare
      - traefik.http.services.librespeed.loadbalancer.server.port=80
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - "PASSWORD={{ status_librespeed_password }}"
    include_global_env_vars: true
    restart: unless-stopped
