roles:
  - src: ironicbadger.bash_aliases
  - src: ironicbadger.proxmox_nag_removal

  - src: geerlingguy.docker
  - src: geerlingguy.docker_arm
  - src: geerlingguy.security
  - src: geerlingguy.nfs
  - src: geerlingguy.ntp
  - src: geerlingguy.github-users

  - src: artis3n.tailscale
  - src: grog.package
  - src: rossmcdonald.telegraf
  - src: weareinteractive.environment
