- src: geerlingguy.docker
- src: geerlingguy.security
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.github-users
- src: grog.package
- src: rossmcdonald.telegraf
- src: ironicbadger.docker_compose_generator
- src: ironicbadger.role_bash_aliases
- src: ironicbadger.hddtemp
- src: ironicbadger.snapraid
- src: ironicbadger.proxmox_nag_removal

- src: ironicbadger.ansible_users
- src: weareinteractive.environment
