---
# - hosts: all
#   roles:
#     - role: ironicbadger.ansible_role_bash_aliases
#   tasks:
#     - name: remove ubuntu motd spam
#       become: true
#       file:
#         path: "/etc/update-motd.d/{{ item }}"
#         state: absent
#       loop:
#         - 80-livepatch
#         - 95-hwe-eol
#         - 10-help-text
#       when: ansible_distribution == 'Ubuntu'

- hosts: pihole
  vars_files:
    - "vars/vault.yaml"
  roles:
    #- role: ironicbadger.figurine
    - role: soul-dhcp-dns

- hosts: caddy
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.ntp
    - role: ironicbadger.figurine
    - role: soulcaddy
      tags: caddy

- hosts: unifi
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.docker
    - role: ironicbadger.bash_aliases
      tags: bash
    - role: ironicbadger.docker-compose-generator
      tags: compose

# soulpms - Perfect Media Server
- hosts: pms
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: ironicbadger.proxmox_nag_removal
    - role: soulhtop
    - role: geerlingguy.docker
    - role: artis3n.tailscale
    - role: grog.package
    #- role: rossmcdonald.telegraf
    - role: ironicbadger.bash_aliases
    #- role: ironicbadger.figurine
    - role: soulboot
    - role: soulzfs
      tags: replication
    - role: soulpms
    - role: ironicbadger.docker-compose-generator
      tags: compose
    - role: soultraefik
      tags: compose
    - role: soulplexmeta
      tags: compose
    - role: soulrecyclarr
      tags: compose
    - role: soulrestic
      tags: replication

# soulcloud
- hosts: cloud
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.docker
    - role: artis3n.tailscale
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: soultraefik
      tags: compose
    - role: ironicbadger.docker-compose-generator
      tags: compose
    - role: soulrestic
      tags: replication

# soulfrigate
- hosts: frigate
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.docker
    #- role: artis3n.tailscale
    - role: ironicbadger.bash_aliases
    #- role: ironicbadger.figurine
    #- role: soulboot
    - role: soultraefik
      tags: compose
    - role: ironicbadger.docker-compose-generator
      tags: compose
    - role: soulrestic
      tags: replication

# soulapps
- hosts: apps
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: geerlingguy.docker
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.figurine
    - role: ironicbadger.proxmox-host-nvidia-setup
    - role: soultraefik
      tags: compose
    - role: ironicbadger.docker-compose-generator
      tags: compose
    - role: soulrestic
      tags: replication

# proxmox
- hosts: proxmox
  vars_files:
    - "vars/vault.yaml"
  roles:
    - role: ironicbadger.proxmox_nag_removal
    - role: soulhtop
