services:
  it-tools:
    image: ghcr.io/corentinth/it-tools
    container_name: it-tools
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tools"
      tsdproxy.port.1: "443/https:80/http"
    restart: unless-stopped
  golink:
    image: ghcr.io/tailscale/golink:main
    container_name: golink
    volumes:
      - "{{ appdata_path }}/golink:/home/nonroot"
    restart: unless-stopped
