services:
  plexmeta:
    image: kometateam/kometa:nightly
    container_name: plexmeta
    labels:
      - traefik.enable=false
    volumes:
      - "{{ appdata_path }}/plexmeta/config:/config"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      - KOMETA_TIMES=01:22
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    depends_on:
      - plex
    labels:
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/tautulli:/config"
      - "{{ appdata_path }}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  seerr:
    image: ghcr.io/seerr-team/seerr
    container_name: seerr
    init: true
    labels:
      - "traefik.http.routers.seerr.rule=Host(`seerr.{{ secret_domain_full }}`)"
    volumes:
      - "{{ appdata_path }}/seerr:/app/config"
    environment:
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
  pulsarr:
    image: lakker/pulsarr
    container_name: pulsarr
    labels:
      - "traefik.http.routers.pulsarr.rule=Host(`pulsarr.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/pulsarr:/app/data"
    environment:
      - baseUrl=http://pulsarr
      - "TZ={{ host_timezone }}"
      - loglevel=info
      - NODE_ARGS=--log-both
      - cookieSecured=true
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    labels:
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/nzbget:/config"
      - "{{ download_path }}:/data/usenet"
      - "/mnt/nvme1/usenet/intermediate:/data/usenet/intermediate"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    labels:
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/prowlarr:/config"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    labels:
      - traefik.enable=false
    ports:
      - "8191:8191"
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    labels:
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/sonarr:/config"
      - "{{ data_path }}:/data"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    depends_on:
      - nzbget
    labels:
      - "traefik.http.routers.radarr.rule=Host(`radarr.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/radarr:/config"
      - "{{ data_path }}:/data"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    depends_on:
      - nzbget
    labels:
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/lidarr:/config"
      - "{{ data_path }}:/data"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    labels:
      - "traefik.http.routers.pinchflat.rule=Host(`yt.p.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/pinchflat:/config"
      - "{{ data_path }}/media/youtube:/downloads"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    depends_on:
      - sonarr
      - radarr
    labels:
      - traefik.enable=false
    volumes:
      - "{{ appdata_path }}/recyclarr:/config"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    labels:
      - "traefik.http.routers.shelfmark.rule=Host(`shelfmark.{{ secret_domain_full }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    volumes:
      - "{{ appdata_path }}/shelfmark/config:/config"
      - "{{ data_path }}:/data"
    restart: unless-stopped
  slskd:
    image: slskd/slskd
    container_name: slskd
    labels:
      - "traefik.http.routers.slskd.rule=Host(`slskd.p.{{ local_domain }}`)"
      - traefik.http.services.slskd.loadbalancer.server.port=5030
    ports:
      - "50300:50300"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - SLSKD_REMOTE_CONFIGURATION=true
      - "SLSKD_USERNAME={{ soulseek_username }}"
      - "SLSKD_PASSWORD={{ secret_slskd_password }}"
      - "SLSKD_API_KEY={{ soulseek_password }}"
      - "SLSKD_SLSK_USERNAME={{ soulseek_username }}"
      - "SLSKD_SLSK_PASSWORD={{ soulseek_password }}"
      - "SLSKD_DOWNLOADS_DIR=/data/soulseek/complete"
      - "SLSKD_INCOMPLETE_DIR=/data/soulseek/downloading"
      - "SLSKD_SHARED_DIR=/data/media/music;/data/media/audiobooks"
    volumes:
      - "{{ appdata_path }}/slskd:/app"
      - "{{ data_path }}:/data"
    restart: unless-stopped
  aurral:
    image: ghcr.io/lklynet/aurral:latest
    container_name: aurral
    labels:
      - "traefik.http.routers.aurral.rule=Host(`aurral.p.{{ local_domain }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "DOWNLOAD_FOLDER={{ data_path }}/media/music/aurral"
      # - "SOULSEEK_USERNAME={{ soulseek_username }}"
      # - "SOULSEEK_PASSWORD={{ soulseek_password }}"
    volumes:
      - "{{ appdata_path }}/aurral:/app/backend/data"
      - "{{ data_path }}/media/music/aurral:/app/downloads"
      - "{{ data_path }}/media/music/library:/data:ro"
    restart: unless-stopped
