---

- name: create /mnt/parity* points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: 
    - "{{ snapraid_parity_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/storage'

- name: create other /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: 0777
  with_items: 
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/nvme1'

- name: mount disks
  mount:
    name: "{{ item.path }}"
    src: "{{ item.diskbyid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/storage'

- name: mount mergerfs array
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ fstab_mergerfs }}"