---

- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/plexmeta/config"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  become: true

- name: template plexmeta rules
  template:
    src: templates/config.yaml.j2
    dest: "{{ appdata_path }}/plexmeta/config/config.yml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  become: true