services:
  tr:
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:172.17.0.1
    environment:
      - "CF_API_KEY={{ secret_cloudflare_api }}"
      - "CF_API_EMAIL={{ secret_cloudflare_email }}"
      - "TRAEFIK_DASHBOARD_CREDENTIALS={{ secret_traefik_dashboard_credentials }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ appdata_path }}/traefik/traefik.yml:/traefik.yml:ro"
      - "{{ appdata_path }}/traefik/acme.json:/acme.json"
      - "{{ appdata_path }}/traefik/rules.yml:/rules.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.p.{{ local_domain }}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users={{ secret_traefik_dashboard_credentials }}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.p.{{ local_domain }}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main={{ secret_domain_full }}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ secret_domain_full }}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    restart: unless-stopped
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: pocket-id
    labels:
      - "traefik.http.routers.pocket-it.rule=Host(`pocket-id.{{ secret_domain_full }}`)"
    environment:
      - "APP_URL=https://pocket-id.{{ secret_domain_full }}"
      - TRUST_PROXY=true
      - "MAXMIND_LICENSE_KEY={{ secret_maxmind_license }}"
      - ENCRYPTION_KEY={{ pocket_id_encryption_key }}
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
    volumes:
      - "{{ appdata_path }}/pocket-id/data:/app/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dockhand.rule=Host(`dockhand.p.{{ local_domain }}`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path }}/dockhand:/app/data"
      - /home/souldeity:/home/souldeity
    restart: unless-stopped
