http:
  routers:
    router-homeassistant:
      entryPoints:
        - websecure
      rule: Host(`home.change.me`)
      service: service-homeassistant
      tls:
        certResolver: cloudflare
  services:
    service-homeassistant:
      loadBalancer:
        servers:
        - url: "http://192.168.1.114:8123"