# Cap ARC size to 50% RAM
zfs_arc_min: "4294967296" #"{{ (ansible_memtotal_mb * 1024 * 1024) * 0.5 }}"
zfs_arc_max: "8589934592"

sanoid_datasets:
  tank/fuse:
    use_template: fuse
    recursive: true

  tank/appdata:
    use_template: appdata
    recursive: true
    process_children_only: true

sanoid_templates:
  fuse:
    frequently: 0
    hourly: 6
    daily: 14
    monthly: 6
    yearly: 0
    autosnap: true
    autoprune: true

  appdata:
    frequently: 0
    hourly: 6
    daily: 7
    monthly: 1
    yearly: 0
    autosnap: true
    autoprune: true