---
- hosts: netkids
  tasks:
    # apt repo updates
    - name: Update packages on all servers
      become: true
      package:
        name: "*"
        state: latest
    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
      when: reboot_required_file.stat.exists
    # docker container updates
    - name: is docker-compose installed?
      command: which docker-compose
      ignore_errors: true
      register: dcp_installed
    - name: container update procedure
      block:
        - name: pull containers
          command: docker-compose pull
        - name: start updated containers
          command: docker-compose up -d
        - name: cleanup old containers
          command: docker system prune --all -f
      when: dcp_installed.rc == 0
    # pihole updates
    - name: is pihole installed?
      command: which pihole
      ignore_errors: true
      register: pihole_installed
    - name: pihole update procedure
      block:
        - name: update pihole
          command: pihole updatePihole
        - name: update gravity
          command: pihole updateGravity
        - name: restartdns
          command: pihole restartdns
      when: pihole_installed.rc == 0
    # caddy updates
    - name: is caddy installed?
      command: which caddy
      ignore_errors: true
      register: caddy_installed
    - name: caddy update procedure
      block:
        - name: update caddy
          command: caddy upgrade
        - name: restart caddy
          systemd: name=caddy state=restarted
      when: caddy_installed.rc == 0
