---

- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/authelia/"
    state: directory
    owner: root
    group: root
  become: true

- name: template authelia config
  template:
    src: templates/users.yml.j2
    dest: "{{ appdata_path }}/authelia/users_database.yml"
    owner: root
    group: root
  become: true

- name: template authelia rules
  template:
    src: templates/configuration.yml.j2
    dest: "{{ appdata_path }}/authelia/configuration.yml"
    owner: "root"
    group: "root"
  become: true